### PR TITLE
Untested: starting naive waypoint updater

### PR DESCRIPTION
**Pull request by abroekhof**
This is untested, more of a way to get our workflow in place. Let's see if we can get through a PR!

### CODE REVIEW

**Review by dehavenm — COMMENTED** [review]
Wait, I thought it was only supposed to publish waypoints ahead of the car. I don't see anything in there that would differentiate between waypoints ahead of or behind the car.

**Comment by abroekhof** [comment]
@dehavenm Thanks for taking a look, you're definitely correct—I'm not sure if it even runs yet! Just wanted to get a commit up, so we could establish a workflow.

**Comment by kjames88** [comment]
I just started with waypoint updater trying to get everything going on my system.  You're a bit ahead of me.  Have we decided on division of labor yet?

**Comment by abroekhof** [comment]
@kjames88 No division of labor yet, let's discuss that over Slack. 

I also haven't had time to get an environment set up, so you may very well have this working before I do. I'm not attached to this code, so feel free to file a PR if you get things working.

**Comment by abroekhof** [comment]
I finally got my environment set up, and fixed the Python bugs. Car is not moving yet, I'm guessing we'll need the control system for that.

**Pull request closed without merging**
